repos:
  - repo: local
    hooks:
      - id: gitleaks-protect
        name: Gitleaks protect staged secrets
        entry: gitleaks protect --staged --redact --verbose
        language: system
        pass_filenames: false
