name: Bug Report
description: Report a bug
labels: ["bug"]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: What happened?
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: How to reproduce the issue.
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: What should have happened.
