#!/usr/bin/env bash
set -euo pipefail
RPC_STATUS=${RPC_STATUS:-0x0}
USDC_TRANSFER_MATCH=${USDC_TRANSFER_MATCH:-0}
BRIDGE_MATCH=${BRIDGE_MATCH:-0}
RECEIPT_MATCH=${RECEIPT_MATCH:-0}
LIVE_MATCH=${LIVE_MATCH:-0}
EXECUTOR_X402_COUNT=${EXECUTOR_X402_COUNT:-0}
MANUAL_MIRROR=${MANUAL_MIRROR:-false}
AUTO_PUBLISHED=${AUTO_PUBLISHED:-false}
VERDICT=FAILED
if [ "$EXECUTOR_X402_COUNT" -gt 1 ]; then VERDICT=BLOCKER
elif [ "$RPC_STATUS" = "0x1" ] && [ "$USDC_TRANSFER_MATCH" = "1" ] && [ "$BRIDGE_MATCH" = "1" ] && [ "$RECEIPT_MATCH" = "1" ] && [ "$LIVE_MATCH" = "1" ] && [ "$EXECUTOR_X402_COUNT" = "1" ] && [ "$MANUAL_MIRROR" = "false" ] && [ "$AUTO_PUBLISHED" = "true" ]; then VERDICT=VERIFIED
elif [ "$LIVE_MATCH" = "0" ]; then VERDICT=PARTIAL
fi
printf 'RPC_STATUS=%s\nUSDC_TRANSFER_MATCH=%s\nBRIDGE_MATCH=%s\nRECEIPT_MATCH=%s\nLIVE_MATCH=%s\nEXECUTOR_X402_COUNT=%s\nMANUAL_MIRROR=%s\nAUTO_PUBLISHED=%s\nVERDICT=%s\n' "$RPC_STATUS" "$USDC_TRANSFER_MATCH" "$BRIDGE_MATCH" "$RECEIPT_MATCH" "$LIVE_MATCH" "$EXECUTOR_X402_COUNT" "$MANUAL_MIRROR" "$AUTO_PUBLISHED" "$VERDICT"
