module.exports = {
  apps: [
    {
      name: "analyzer-hi-freq",
      script: "run-buyer-hi-freq.js",
      interpreter: "node",
      cwd: __dirname,
      env: {
        BOT_CONFIG: "bot.config.analyzer.json",
        AGENT_ROLE: "analyzer",
        AGENT_CATEGORY: "prediction-market-bots",
        MARKET_ID: "btc-15m",
        ARCLAYER_AGENT_ID: "apollo-analyzer",
        ARCLAYER_API_KEY: process.env.ARCLAYER_API_KEY_ANALYZER || "",
        PRIVATE_KEY: process.env.BOT_PRIVATE_KEY_ANALYZER || "",
        X402_PAYER_PRIVATE_KEY: process.env.BOT_PRIVATE_KEY_ANALYZER || "",
        UPSTREAM_AGENT_ID: "hermes-oracle",
        UPSTREAM_ROLE: "oracle",
        RUNTIME_ID: "circle-commerce-analyzer-01",
        LLM_MODEL: process.env.LLM_MODEL || "xiaomi/mimo-v2-flash",
      },
      autorestart: true,
      max_memory_restart: "200M",
    },
    {
      name: "evaluator-hi-freq",
      script: "run-buyer-hi-freq.js",
      interpreter: "node",
      cwd: __dirname,
      env: {
        BOT_CONFIG: "bot.config.evaluator.json",
        AGENT_ROLE: "evaluator",
        AGENT_CATEGORY: "prediction-market-bots",
        MARKET_ID: "btc-15m",
        ARCLAYER_AGENT_ID: "ignia-evaluator",
        ARCLAYER_API_KEY: process.env.ARCLAYER_API_KEY_EVALUATOR || "",
        PRIVATE_KEY: process.env.BOT_PRIVATE_KEY_EVALUATOR || "",
        X402_PAYER_PRIVATE_KEY: process.env.BOT_PRIVATE_KEY_EVALUATOR || "",
        UPSTREAM_AGENT_ID: "apollo-analyzer",
        UPSTREAM_ROLE: "analyzer",
        RUNTIME_ID: "circle-commerce-evaluator-01",
        LLM_MODEL: process.env.LLM_MODEL || "xiaomi/mimo-v2-flash",
      },
      autorestart: true,
      max_memory_restart: "200M",
    },
  ],
};
