/**
 * Arc/Circle Separation Lock Tests
 *
 * Ensures:
 * - circle.chain does NOT select Arc contract addresses
 * - erc8183ContractAddress is NOT generated by init
 * - setup does NOT ask for contract address
 * - doctor warns if deprecated fields are set
 * - provider_run_and_submit uses SDK constants only
 */

import { describe, it, expect } from "vitest";
import { CONTRACTS } from "@arclayer/sdk";
import { RunnerConfigSchema, InitFileConfigSchema, transformFileConfig, PolicyConfigSchema } from "@arclayer/runner-core";

describe("Arc/Circle separation lock", () => {
  const defaultPolicy = PolicyConfigSchema.parse({});

  it("SDK CONTRACTS.ERC8183_AGENTIC_COMMERCE is defined", () => {
    expect(CONTRACTS.ERC8183_AGENTIC_COMMERCE).toBeDefined();
    expect(CONTRACTS.ERC8183_AGENTIC_COMMERCE).toMatch(/^0x[0-9a-fA-F]{40}$/);
  });

  it("RunnerConfigSchema has erc8183ContractAddress as optional deprecated", () => {
    // The field exists for backward compat but is optional
    const parsed = RunnerConfigSchema.parse({
      agentId: "test",
      runnerId: "runner-test",
      runnerSecret: "test-secret-at-least-16",
      defaultRole: "provider",
      agentAddress: "0x0000000000000000000000000000000000000000",
      runtimeKind: "openclaw",
      runtimeEndpoint: "http://127.0.0.1:8787",
    });
    // Should parse without erc8183ContractAddress
    expect(parsed.agentId).toBe("test");
    // erc8183ContractAddress should be undefined when not provided
    expect((parsed as any).erc8183ContractAddress).toBeUndefined();
  });

  it("InitFileConfigSchema does NOT include erc8183ContractAddress", () => {
    // Nested config should strip unknown fields
    const parsed = InitFileConfigSchema.parse({
      agentId: "test",
      role: "provider",
      erc8183ContractAddress: "0x0747EEf0706327138c69792bF28Cd525089e4583",
    });
    // Zod strips unknown fields by default
    expect((parsed as any).erc8183ContractAddress).toBeUndefined();
  });

  it("transformFileConfig does NOT pass erc8183ContractAddress", () => {
    const config = InitFileConfigSchema.parse({
      agentId: "test",
      role: "provider",
    });
    const flat = transformFileConfig(config, defaultPolicy);
    expect(flat.erc8183ContractAddress).toBeUndefined();
  });

  it("circle.chain does NOT affect contract address selection", () => {
    // Verify that CONTRACTS constant is independent of chain
    const baseAddr = CONTRACTS.ERC8183_AGENTIC_COMMERCE;
    expect(baseAddr).toBe("0x0747EEf0706327138c69792bF28Cd525089e4583");
    // This should be the same regardless of chain config
    // (it's a constant, not derived from chain)
  });

  it("RunnerConfigSchema does NOT have contractAddress override", () => {
    const shape = RunnerConfigSchema.shape;
    // There should be no generic contractAddress field
    expect((shape as any).contractAddress).toBeUndefined();
  });
});
